import { Burger } from "@/types/burger";

export const BURGERS: Burger[] = [
  {
    id: "b-1",
    name: "The Royal Truffle Smash",
    tagline: "Double Angus Beef • Aged Swiss • White Truffle Aioli",
    description: "Two 100% Black Angus beef smash patties topped with melted aged Swiss cheese, caramelized balsamic onions, and rich white truffle aioli served on a toasted artisanal brioche bun.",
    price: 15.99,
    originalPrice: 18.99,
    rating: 4.9,
    reviewsCount: 342,
    categoryId: "smash",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    calories: 840,
    prepTimeMinutes: 12,
    tags: ["Chef Pick", "Double Patty", "Truffle"],
    ingredients: ["Double Black Angus Beef", "Aged Swiss Cheese", "Caramelized Onions", "White Truffle Aioli", "Brioche Bun"],
  },
  {
    id: "b-2",
    name: "Firehouse Diablo Inferno",
    tagline: "Triple Pepper Jack • Smoked Bacon • Ghost Chili Glaze",
    description: "Flame-grilled beef patty, spicy pepper jack cheese, crispy applewood smoked bacon, jalapeño poppers, and our signature fiery ghost chili secret glaze.",
    price: 14.49,
    rating: 4.8,
    reviewsCount: 218,
    categoryId: "signature",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isSpicy: true,
    calories: 920,
    prepTimeMinutes: 15,
    tags: ["Extra Spicy", "Flame-Grilled", "Bacon"],
    ingredients: ["Prime Beef Patty", "Pepper Jack Cheese", "Applewood Bacon", "Jalapeño Poppers", "Ghost Chili Sauce"],
  },
  {
    id: "b-3",
    name: "Honey Chipotle Crispy Chicken",
    tagline: "Buttermilk Fried Chicken • Honey Glaze • Dill Pickles",
    description: "Crispy buttermilk-fried chicken breast tossed in hot honey chipotle glaze, creamy purple cabbage slaw, and thick-cut crinkle dill pickles.",
    price: 13.99,
    originalPrice: 15.49,
    rating: 4.9,
    reviewsCount: 412,
    categoryId: "chicken",
    image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    calories: 780,
    prepTimeMinutes: 10,
    tags: ["Crispy", "Hot Honey", "Top Rated"],
    ingredients: ["Buttermilk Chicken", "Hot Honey Chipotle", "Purple Slaw", "Dill Pickles", "Toasted Bun"],
  },
  {
    id: "b-4",
    name: "The Classic Flame Monster",
    tagline: "Single Angus • Double American Cheese • House Relish",
    description: "Classic flame-broiled beef patty loaded with melted American cheese, crisp lettuce, ripe vine tomatoes, red onion rings, and classic thousand island house sauce.",
    price: 11.99,
    rating: 4.7,
    reviewsCount: 189,
    categoryId: "signature",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    calories: 690,
    prepTimeMinutes: 10,
    tags: ["Classic", "Best Value"],
    ingredients: ["Flame-Grilled Beef", "American Cheese", "Vine Tomatoes", "Crisp Lettuce", "House Sauce"],
  },
  {
    id: "b-5",
    name: "Ultimate Beyond Garden Beast",
    tagline: "100% Plant Patty • Vegan Cheddar • Avocado Mash",
    description: "Seared Beyond Meat patty topped with melted vegan cheddar, fresh Hass avocado smash, heirloom tomato, baby arugula, and lemon herb garlic sauce.",
    price: 14.99,
    rating: 4.8,
    reviewsCount: 156,
    categoryId: "plant",
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=800&q=80",
    isVeg: true,
    calories: 610,
    prepTimeMinutes: 12,
    tags: ["100% Vegan", "Avocado", "Healthy"],
    ingredients: ["Beyond Meat Patty", "Vegan Cheddar", "Avocado Smash", "Heirloom Tomato", "Herb Sauce"],
  },
  {
    id: "b-6",
    name: "Smokey BBQ Bacon Monster",
    tagline: "Double Beef • Smoked Gouda • Crispy Onion Strings",
    description: "Two juicy patties drenched in hickory smoked BBQ glaze, thick crispy bacon strips, melted smoked gouda cheese, and golden fried onion strings.",
    price: 16.49,
    originalPrice: 19.49,
    rating: 4.9,
    reviewsCount: 520,
    categoryId: "smash",
    image: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isNew: true,
    calories: 980,
    prepTimeMinutes: 14,
    tags: ["BBQ", "Loaded", "Fan Favorite"],
    ingredients: ["Double Angus Beef", "Crispy Bacon", "Smoked Gouda", "BBQ Sauce", "Onion Strings"],
  },
];
